### ISSUE TITLE
Multiple Stream Situation

### ISSUE THREAD

**Issue by Brazedowl** [adilinden-oss/octoprint-webcamstreamer#24]
I'm a high school teacher and have six (at the moment) printers with cams up and going. I love the idea of streaming while printing to share with the community what is going on in our building. Youtube only allows one live stream at a time, but that's really ok.

**Way it works now:** First printer to start printing starts up the stream. If another printer starts printing it also starts a stream. Nothing happens until the first printer stops, then the next one takes over the stream seamlessly. It's pretty slick. I just hope it's intentional, and not an artifact of an unexpected setup. 

I really just wanted to mention the situation so that the multiple stream situation could be taken into account while you're completing future updates. I'd hate for you to fix one bug, but cause an unexpected cascade of code that somehow stops this from working as it does now just because you may not have thought about this type of situation. The only feature I could think to add related to this is maybe a way to prioritize a printer so it could somehow take over the stream? But that would require the RPis to communicate to tell the other to shut off the stream. So I'm not sure if that's even possible or in the scope of your plans. :)

Thank you for all the hard work you put into this plugin and I really appreciate it!

EDIT: One thing that would be nice is if the web streamer could put text into the stream itself. So I could label it as "Printer #1 - <model name>" to provide a little more info to the viewer. :)

**Comment by adilinden** [comment]
Thank you for providing this insight. What YouTube does when multiple streams converge at the same streaming URL would be determined by YouTube in how it ingests streams. I don't believe there is anything one could do on the streamer side to influence that decision.

I do know YouTube has a live events feature that is supposed to allow for multiple camera views of the same event. Another workaround would be a dedicated YouTube channel for each printer.
