### ISSUE TITLE
Plug-in installs but doesn't show a new item in the list of plug-ins to configure

### ISSUE THREAD

**Issue by rubin110** [adilinden-oss/octoprint-webcamstreamer#27]
After installing the plug-in and restarting Octoprint, I don't see any items related to it under the list of plug-ins to configure on the left menu of the configuration modal. I do see that it is installed in the installed plug-ins list. Not sure where to begin debugging this?

**Comment by adilinden** [comment]
I am sorry, no idea how to assist. I installed OctoPi on a rPi 4 and loaded the plugin also. All worked just fine.
