### ISSUE TITLE
Feature request: Update the stream title with the name of the print

### ISSUE THREAD

**Issue by MacCracken** [adilinden-oss/octoprint-webcamstreamer#31]
Was trying to look at the code to figure out if there was an easy way to update the stream title when starting the stream.  Either as a configurable option from the plugin area; or just using the name of the print in progress as the stream title.

**Comment by adilinden** [comment]
I did something like it, but it wouldn't run on my rPi 2. Now that I have resurrected my 3D printer and have upgraded to a rPi  4 I might just tackle it. For reference, [this](https://github.com/adilinden-oss/docker-octoprint-streamer) **will not run on Raspberry Pi** but adds text info and royalty free music.
