### ISSUE TITLE
Are there faster ffmpeg encode/copy setting settings for rpi4?

### ISSUE THREAD

**Issue by mpalpha** [adilinden-oss/octoprint-webcamstreamer#34]
my current ffmpeg settings are:
```ffmpeg -re -f mjpeg -framerate {frame_rate} -i {webcam_url} -ar 44100 -ac 2 -acodec pcm_s16le -f s16le -ac 2 -i /dev/zero -acodec aac -ab 128k -strict experimental -vcodec h264_omx -pix_fmt yuv420p  -framerate {frame_rate} -g 4 -vb 2500k -f flv {stream_url}```

**Comment by adilinden** [comment]
`ffmpeg -re -f mjpeg -framerate 5 -i {webcam_url} -ar 44100 -ac 2 -acodec pcm_s16le -f s16le -ac 2 -i /dev/zero -acodec aac -ab 128k -vcodec h264 -pix_fmt yuv420p -framerate 5 -g 10 -strict experimental -filter:v null -f flv {stream_url}` is what I am currently using.  It does use OMX hardware acceleration.

```
[h264_omx @ 0x1acaf10] Using OMX.broadcom.video_encode
Output #0, flv, to '<stream URL>':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (h264_omx) ([7][0][0][0] / 0x0007), yuv420p(progressive), 640x480, q=2-31, 200 kb/s, 5 fps, 1k tbn, 5 tbc
    Metadata:
      encoder         : Lavc58.35.100 h264_omx
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc58.35.100 aac
```

This is using the `ffmpeg` docker image from `https://hub.docker.com/r/adilinden/rpi-ffmpeg`.
