### ISSUE TITLE
Is this addon abandoned? 

### ISSUE THREAD

**Issue by mjrider** [adilinden-oss/octoprint-webcamstreamer#35]
Hello,

Is this plugin still under maintenance?

There are a few PR's with outstanding with no response and there is no development since a long time ago. 

If it is, please mark this repository as archived or open the plugin for adoption

**Comment by adilinden** [comment]
I currently do not have a working 3D printer due to ongoing renovations. Means I am in no position to actually test anything. If there are willing participants that would like to continue development, I would welcome additional maintainers.

**Comment by adilinden** [comment]
https://hub.docker.com/r/adilinden/rpi-ffmpeg exists again.
