### ISSUE TITLE
How do you find the URL for your webcam?

### ISSUE THREAD

**Issue by renegadecitizen** [adilinden-oss/octoprint-webcamstreamer#38]
How do you find the URL for your webcam?

**Comment by kolisko** [comment]
@renegadecitizen it should be something like http://yourOctopiServer/webcam/?action=stream

**Comment by adilinden** [comment]
You will find it in settings under "Webcam & Timelapse"

![image](https://user-images.githubusercontent.com/1149715/153344634-50725238-dc2f-4379-b38e-1a58678363c2.png)
