### ISSUE TITLE
repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by ttrueten** [adilinden-oss/octoprint-webcamstreamer#39]
Hello,
i get the following response: 
`pi@octopi:~ $ docker pull adilinden/rpi-stream:latest
Error response from daemon: pull access denied for adilinden/rpi-stream, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

Any hints?

Cheers,
Thomas

**Comment by spence572** [comment]
https://github.com/adilinden-oss/octoprint-webcamstreamer/issues/36#issuecomment-723980053

**Comment by kolisko** [comment]
@ttrueten I created the PR adilinden-oss/docker-ffmpeg#1 fix and built the kolisko/rpi-stream image

**Comment by CobaltEcho** [comment]
@kolisko Is there a way to install your fix and use it currently?

Nevermind, followed the other link and actually read stuff.

For those who find themselves here:  In the settings for the streamer, change `adilinden/rpi-ffmpeg:latest`  to  `kolisko/rpi-ffmpeg:latest`

**Comment by kolisko** [comment]
@CobaltEcho Yes, it should work exactly as you described

**Comment by foosel** [comment]
We also just got a report about this on the OctoPrint plugin repository:

https://github.com/OctoPrint/plugins.octoprint.org/issues/784

@adilinden-oss are you still actively maintaining this plugin? If so, could you please either fix your docker repository or update the README and your plugin listing to a working state? Thank you.

**Comment by adilinden** [comment]
https://hub.docker.com/r/adilinden/rpi-ffmpeg exists again and has working images.
